<?php

namespace panix\mod\user\models\forms;

use Yii;
use panix\engine\SettingsModel;
use yii\helpers\ArrayHelper;

/**
 * Class SettingsForm
 * @package panix\mod\user\models\forms
 */
class SettingsForm extends SettingsModel
{

    public static $category = 'user';
    protected $module = 'user';

    public $login_duration;
    public $enable_register;
    public $enable_forgot;
    public $enable_social_auth;
    public $mail_forgot;

    public $oauth_facebook_id;
    public $oauth_facebook_secret;

    public $oauth_google_id;
    public $oauth_google_secret;

    public $oauth_vkontakte_id;
    public $oauth_vkontakte_secret;

    public $oauth_github_id;
    public $oauth_github_secret;

    public $oauth_yandex_id;
    public $oauth_yandex_secret;

    public $oauth_twitter_id;
    public $oauth_twitter_secret;

    public $oauth_linkedin_id;
    public $oauth_linkedin_secret;

    public $oauth_live_id;
    public $oauth_live_secret;


    public $page_agreement;

    public $bonus_ratio;
    public $bonus_value;
    public $bonus_max_use_order;
    public $bonus_expire_days;
    public $bonus_register_value;
    public $bonus_comment_value;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['bonus_expire_days','bonus_max_use_order'], "integer"],
            [['bonus_ratio','bonus_value','bonus_register_value','bonus_comment_value'], "number"],

            [['login_duration'], "required"],
            [['login_duration','page_agreement'], 'integer'],
            [['enable_register', 'enable_forgot', 'enable_social_auth'], 'boolean'],
            [['mail_forgot'], 'string'],
            [['oauth_facebook_id', 'oauth_google_id', 'oauth_vkontakte_id', 'oauth_github_id', 'oauth_yandex_id', 'oauth_twitter_id', 'oauth_linkedin_id', 'oauth_live_id'], 'string'],
            [['oauth_facebook_secret', 'oauth_google_secret', 'oauth_vkontakte_secret', 'oauth_github_secret', 'oauth_yandex_secret', 'oauth_twitter_secret', 'oauth_linkedin_secret', 'oauth_live_secret'], 'string'],
        ];
    }

    /**
     * Настройки по умолчанию
     * @return array
     */
    public static function defaultSettings()
    {
        return [
            'login_duration' => 30,
            'enable_register' => 1,
            'enable_forgot' => 1,
            'enable_social_auth' => 0,
            'bonus_max_use_order' => 50,
            'bonus_ratio' => 0.05,
            'bonus_expire_days' => 90,
            'bonus_value' => 1,
            'bonus_register_value' => 30,
            'bonus_comment_value' => 10,
            'page_agreement' => null,
        ];
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(),['bonus_ratio'=>self::t('BONUS_RATIO',['currency'=>Yii::$app->currency->main['symbol']])]); // TODO: Change the autogenerated stub
    }

}